/** T-04 / FR-U01·U02 锁句（T-03 API + T-07 屏 6/7/9/10/11/23）。禁止 FR-U24 四字。 */

export const EMPTY_RESULTS_COPY = '还没有结果，去提交采集'
export const GO_SUBMIT_COLLECT = '去提交采集'
export const FILTERED_RESULTS_EMPTY = '没有符合条件的结果'
export const CLEAR_FILTERS = '清除筛选'

export const EMPTY_TASKS_COPY = '还没有采集任务。新增任务或去采集向导创建一个。'
export const FILTERED_TASKS_EMPTY = '没有符合条件的任务'

export const SPIDER_WORKER_OFFLINE_COPY = '采集未运行，不会出数'
export const VIEW_NODES_TEXT = '查看节点'

export const PLAN_FULL_COPY = '已达配额上限'
export const NEAR_LIMIT_COPY = '接近上限。超额操作会被拒绝。'
export const UPGRADE_CTA = '申请提升'
export const STORAGE_CTA = '去结果库'
export const ENQUEUED_COPY = '已入队'
export const SUBMITTING_COPY = '提交中…'
export const PLANNING_COPY = '规划中…'

export const CONTACT_ADMIN_COPY = '请联系本企业管理员开通'
export const CONTACT_ADMIN_DETAIL = '开通套餐或中转需要本企业管理员操作。当前账号不能创建支付。'
export const CONTACT_ADMIN_OK = '知道了'

export const CHECKOUT_EMPTY_COPY = '收款通道未开通'
export const CHECKOUT_EMPTY_DETAIL = '现在还不能用支付宝或微信支付。开通后回到本页继续。'
export const CHECKOUT_OPEN_FAILED = '结账打开失败，请稍后重试。'
export const CHECKOUT_UNKNOWN_PRODUCT = '没有这个商品。'
export const CHECKOUT_PATH_PRO = '/billing/checkout?product=plan_pro'
export const CHECKOUT_PATH_ENTERPRISE = '/billing/checkout?product=plan_enterprise'
export const CHECKOUT_PATH_RELAY = '/billing/checkout?product=relay'
export const DEFAULT_UPGRADE_PRODUCT = 'plan_pro'
export const CHECKOUT_PRODUCTS = ['plan_pro', 'plan_enterprise', 'relay'] as const

export const CHANNEL_ALIPAY = '支付宝'
export const CHANNEL_WECHAT = '微信支付'
export const CHANNEL_UNCONFIGURED_COPY = '该通道未开通'
export const CHECKOUT_GO_PAY = '去支付'
export const CHECKOUT_GO_PAY_LOADING = '去支付…'
export const CHECKOUT_CONTINUE_PAY = '继续支付'
export const CHECKOUT_PENDING_COPY = '待支付'
export const CHECKOUT_PENDING_EXISTS_COPY = '已有未完成的支付'
export const CHECKOUT_PAID_PENDING_COPY = '支付已到账，开通处理中'
export const CHECKOUT_UNPAID_PLAN = '支付未完成，套餐未开通'
export const CHECKOUT_UNPAID_RELAY = '支付未完成，中转未开通'
export const CHECKOUT_RETRY_CHECKOUT = '重新去结账'
export const CHECKOUT_RETURN_PRICING = '返回定价'
export const CHECKOUT_OFFLINE_OPEN = '网络不可用。连接恢复后再打开结账。'
export const CHECKOUT_OFFLINE_PAY = '网络不可用，没有创建待支付。'
export const CHECKOUT_OFFLINE_CONTINUE = '网络不可用，没有进入通道。'
export const CHECKOUT_REFRESH = '刷新'
export const PRICING_CTA_CHECKOUT = '去结账'
export const PRICING_CTA_REGISTER = '免费注册'
export const PRICING_PATH = '/pricing'

export const TASK_QUOTA_LIMIT_CODE = 'TASK_QUOTA_LIMIT_REACHED'
export const SPIDER_WORKER_OFFLINE_CODE = 'SPIDER_WORKER_OFFLINE'
export const ORDER_ROLE_NOT_ALLOWED = 'ORDER_ROLE_NOT_ALLOWED'
export const BILLING_CHANNELS_UNCONFIGURED = 'BILLING_CHANNELS_UNCONFIGURED'
export const BILLING_CHANNEL_UNCONFIGURED = 'BILLING_CHANNEL_UNCONFIGURED'
export const CHECKOUT_PENDING_EXISTS = 'CHECKOUT_PENDING_EXISTS'
export const CHECKOUT_SUPERADMIN_FORBIDDEN = 'CHECKOUT_SUPERADMIN_FORBIDDEN'

export const UPGRADE_OFFLINE_COPY = '网络不可用。连接恢复后再申请提升。'
export const SUBMIT_OFFLINE_COPY = '网络不可用，任务没有入队。'
