"""add product_events table

Revision ID: 031
Revises: 027
Create Date: 2026-09-08

Wave 0 T-12 / ADR-0016：产品事实 OLTP 追加表。autogenerate（include_object 仅
product_events）；v1 无精确一次键。禁止复活 028/029/030 pyc。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "031"
down_revision: Union[str, Sequence[str], None] = "027"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='代理主键，跟仓 INT'),
    sa.Column('occurred_at', sa.DateTime(), nullable=False, comment='业务时间 UTC；切日 Asia/Shanghai'),
    sa.Column('event_name', sa.String(length=64), nullable=False, comment='蓝图字面量；dba 不改口径'),
    sa.Column('tenant_id', sa.Integer(), nullable=True, comment='NULL=匿名或无法消歧。事件主语，非隔离归属'),
    sa.Column('actor_user_id', sa.Integer(), nullable=True, comment='匿名 NULL；不加 FK'),
    sa.Column('anonymous_id', sa.String(length=64), nullable=True, comment='浏览匿名身份；signup 必须带回'),
    sa.Column('role', sa.String(length=32), nullable=True, comment='已登录才有'),
    sa.Column('props', sa.JSON(), nullable=True, comment='非查询列：cta/page/spider/source/result_count/...'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='记录时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='R-AUD；应用永不更新'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_events_name_occurred', 'product_events', ['event_name', 'occurred_at'], unique=False)
    op.create_index('idx_product_events_tenant_occurred', 'product_events', ['tenant_id', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_product_events_tenant_occurred', table_name='product_events')
    op.drop_index('idx_product_events_name_occurred', table_name='product_events')
    op.drop_table('product_events')
    # ### end Alembic commands ###
