"""t21 capability commands components

Revision ID: 033
Revises: 032
Create Date: 2026-09-09

T-21 平台目录表：capability_commands / capability_components。
autogenerate（include_object 仅这两表；stamp 032 空库对比）。
禁止复活 028/029/030。不改 uq_asset_type_name_alive。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "033"
down_revision: Union[str, Sequence[str], None] = "032"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capability_commands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('slash', sa.String(length=64), nullable=False, comment='非全局唯一'),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('body_md', sa.Text(), nullable=True, comment='命令正文；本表即侧表'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['capability_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', name='uq_commands_asset')
    )
    op.create_table('capability_components',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_asset_id', sa.Integer(), nullable=False),
    sa.Column('child_asset_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False, comment='bundled_skill/command/agent|uses_skill|team_member'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['child_asset_id'], ['capability_assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_asset_id'], ['capability_assets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_asset_id', 'child_asset_id', name='uq_components_parent_child')
    )
    op.create_index('idx_components_child', 'capability_components', ['child_asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_components_child', table_name='capability_components')
    op.drop_table('capability_components')
    op.drop_table('capability_commands')
    # ### end Alembic commands ###
